version: '3.8'

services:
  # Servicio de producción
  api:
    build: .
    image: skarious/audio-transcription-api:0.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped